## **■　よくわかる寺子屋セミナー　第2回　データの読み込みと書き出し**

In [1]:
# 数値計算
1+1

2

In [2]:
# かけ算は * を使う
2 * 4

8

# 0. ドライブにマウント

In [4]:
# 今自分はどこにいるか
!pwd

/content

In [5]:
# current directoryに何があるか
!ls

drive  sample_data

In [6]:
# 今自分はなにをしているか
!cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

# 1. 環境設定

In [7]:
# Libraryの読み込み
import numpy as np
import pandas as pd

In [8]:
# Excelを入出力するためのmoduleのインストール
!pip install openpyxl
!pip install xlrd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: openpyxl in /usr/local/lib/python3.7/dist-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl) (1.1.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)

# 2. データの入出力

In [14]:
# csvファイルの読み込み(入力)
df = pd.read_csv('/content/drive/MyDrive/Telakoya/data/data.csv')

In [10]:
# ファイルの書き出し(出力)
df.to_csv('/content/drive/MyDrive/Telakoya/result/data.csv')

In [12]:
# encodingのエラーへの対処
df = pd.read_csv('/content/drive/MyDrive/Telakoya/data/sample.csv', encoding = 'unicode_escape')

# 3. メソッドの演習

In [15]:
# 単にDataFrameを出力させてみる
df

,ID,factor1,factor2,factor3,factor4,factor5,factor6,factor7,factor8,factor9,...,factor141,factor142,factor143,factor144,factor145,factor146,factor147,factor148,factor149,factor150
0,ID1,NaN,NaN,A,NaN,NaN,1.241863,B,NaN,0.984801,...,1.369706,3.965898,C,3.511195,A,NaN,4.951736,1.259221,0.773287,1.028736
1,ID2,C,Z,Z,0.283582,A,0.243880,Z,A,2.599852,...,3.351286,1.501172,Z,1.029643,A,4.022659,1.036468,0.221097,0.976044,2.983533
2,ID3,A,A,C,3.175930,C,4.365006,A,C,1.650896,...,3.175930,4.225075,C,1.944667,Z,0.651723,4.186858,NaN,2.434897,4.520745
3,ID4,A,Z,A,1.566577,A,2.983811,C,Z,NaN,...,4.724513,2.689592,B,1.428877,C,1.286300,NaN,4.652309,1.428877,3.362870
4,ID5,C,Z,NaN,0.464134,Z,2.191147,NaN,B,4.382401,...,3.137875,4.642228,NaN,4.684253,Z,0.708323,0.808047,0.581696,4.782386,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,ID14996,B,Z,NaN,2.197228,NaN,4.384694,C,A,NaN,...,2.588611,2.877683,B,4.781191,NaN,0.224341,0.143134,2.340001,0.224341,4.952754
14996,ID14997,A,C,A,4.077054,Z,0.445390,C,NaN,2.824001,...,0.779132,0.491730,NaN,NaN,Z,2.614576,2.299104,2.843733,4.201130,0.097627
14997,ID14998,A,C,Z,1.407224,B,2.360011,B,A,2.511333,...,2.044176,2.511333,Z,3.706377,B,NaN,1.562139,4.859076,4.932989,0.391659
14998,ID14999,NaN,NaN,Z,NaN,A,4.059424,NaN,NaN,2.878456,...,NaN,4.732487,B,NaN,B,4.666555,2.699051,1.314517,2.407777,2.731233
14999,ID15000,A,B,A,4.072493,A,4.335164,C,C,3.738258,...,2.143087,4.569763,B,1.045792,B,NaN,4.319808,3.945508,0.957288,NaN

In [17]:
# 最初から20行のデータの表示
df.head(20)

,ID,factor1,factor2,factor3,factor4,factor5,factor6,factor7,factor8,factor9,...,factor141,factor142,factor143,factor144,factor145,factor146,factor147,factor148,factor149,factor150
0,ID1,NaN,NaN,A,NaN,NaN,1.241863,B,NaN,0.984801,...,1.369706,3.965898,C,3.511195,A,NaN,4.951736,1.259221,0.773287,1.028736
1,ID2,C,Z,Z,0.283582,A,0.243880,Z,A,2.599852,...,3.351286,1.501172,Z,1.029643,A,4.022659,1.036468,0.221097,0.976044,2.983533
2,ID3,A,A,C,3.175930,C,4.365006,A,C,1.650896,...,3.175930,4.225075,C,1.944667,Z,0.651723,4.186858,NaN,2.434897,4.520745
3,ID4,A,Z,A,1.566577,A,2.983811,C,Z,NaN,...,4.724513,2.689592,B,1.428877,C,1.286300,NaN,4.652309,1.428877,3.362870
4,ID5,C,Z,NaN,0.464134,Z,2.191147,NaN,B,4.382401,...,3.137875,4.642228,NaN,4.684253,Z,0.708323,0.808047,0.581696,4.782386,NaN
5,ID6,Z,Z,Z,4.096361,A,1.549590,NaN,B,2.339750,...,4.402666,1.707958,A,3.501586,A,3.749315,0.557002,1.101343,4.299159,0.938373
6,ID7,NaN,B,Z,2.162318,A,1.356833,C,A,4.691786,...,0.585652,4.417323,NaN,4.392648,NaN,1.702492,3.222163,0.563609,2.518862,4.205691
7,ID8,A,Z,Z,3.015889,B,NaN,NaN,C,4.719366,...,2.699121,NaN,B,2.297406,Z,4.995464,0.419017,2.372937,4.988565,2.585732
8,ID9,A,NaN,A,4.764512,A,NaN,Z,A,4.391872,...,0.591030,0.054777,B,4.285026,Z,4.880026,3.890645,NaN,NaN,1.708590
9,ID10,NaN,Z,B,3.524959,B,0.063331,A,C,4.310171,...,2.034784,2.164489,Z,NaN,C,1.727188,NaN,NaN,4.695228,2.686666
10,ID11,Z,B,C,1.270760,C,2.090642,Z,C,0.197699,...,2.467253,NaN,B,NaN,NaN,2.644460,4.988670,0.781252,2.599966,3.997578
11,ID12,A,Z,Z,4.313468,B,2.062442,B,A,4.800547,...,4.550498,1.058384,B,3.226648,A,1.299408,NaN,3.083665,4.550498,3.579807
12,ID13,C,Z,B,2.110541,NaN,4.062920,C,C,1.576380,...,1.930298,0.027957,Z,NaN,NaN,1.464364,3.428484,0.164768,2.183411,1.257897
13,ID14,Z,A,C,0.317628,Z,0.064822,NaN,A,1.510149,...,0.494898,0.803121,C,3.792590,NaN,4.397610,1.745028,4.389906,1.686977,NaN
14,ID15,Z,A,NaN,4.398261,A,1.681874,Z,B,3.021999,...,4.103388,3.674124,C,3.455148,B,3.963641,4.872261,3.458036,1.231885,1.181045
15,ID16,Z,Z,Z,NaN,A,NaN,C,B,2.321013,...,3.706163,NaN,Z,2.600026,B,3.872362,NaN,NaN,NaN,1.894296
16,ID17,C,B,NaN,NaN,Z,0.302974,C,Z,1.447349,...,2.965094,0.307363,Z,0.343846,Z,2.583744,NaN,2.775995,2.627961,1.423598
17,ID18,NaN,NaN,B,0.527283,Z,NaN,A,A,3.019523,...,1.438101,1.562819,Z,2.866819,B,0.245141,3.611309,NaN,3.804652,NaN
18,ID19,A,A,NaN,3.004842,Z,4.139683,Z,Z,2.558057,...,NaN,3.936546,Z,3.257906,NaN,0.954894,3.936546,0.835560,1.225949,2.807041
19,ID20,Z,B,C,4.406738,NaN,1.560162,Z,A,1.419762,...,2.619903,1.560162,A,NaN,C,NaN,NaN,0.078939,2.700742,4.394031

In [18]:
# 最後から5行のデータの表示
df.tail()

,ID,factor1,factor2,factor3,factor4,factor5,factor6,factor7,factor8,factor9,...,factor141,factor142,factor143,factor144,factor145,factor146,factor147,factor148,factor149,factor150
14995,ID14996,B,Z,NaN,2.197228,NaN,4.384694,C,A,NaN,...,2.588611,2.877683,B,4.781191,NaN,0.224341,0.143134,2.340001,0.224341,4.952754
14996,ID14997,A,C,A,4.077054,Z,0.445390,C,NaN,2.824001,...,0.779132,0.491730,NaN,NaN,Z,2.614576,2.299104,2.843733,4.201130,0.097627
14997,ID14998,A,C,Z,1.407224,B,2.360011,B,A,2.511333,...,2.044176,2.511333,Z,3.706377,B,NaN,1.562139,4.859076,4.932989,0.391659
14998,ID14999,NaN,NaN,Z,NaN,A,4.059424,NaN,NaN,2.878456,...,NaN,4.732487,B,NaN,B,4.666555,2.699051,1.314517,2.407777,2.731233
14999,ID15000,A,B,A,4.072493,A,4.335164,C,C,3.738258,...,2.143087,4.569763,B,1.045792,B,NaN,4.319808,3.945508,0.957288,NaN

In [19]:
# データのタイプの確認
type(df)

pandas.core.frame.DataFrame

In [20]:
# データの行と列の数の確認
df.shape

(15000, 151)

In [21]:
# データの情報
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Columns: 151 entries, ID to factor150
dtypes: float64(75), object(76)
memory usage: 17.3+ MB

In [22]:
# 容量が大きい場合
df.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Columns: 151 entries, ID to factor150
dtypes: float64(75), object(76)
memory usage: 66.1 MB

In [23]:
# 統計量の算出
df.describe()

,factor4,factor6,factor9,factor10,factor11,factor12,factor15,factor18,factor19,factor20,...,factor134,factor136,factor141,factor142,factor144,factor146,factor147,factor148,factor149,factor150
count,1.254400e+04,12514.000000,12511.000000,12526.000000,12500.000000,12524.000000,12465.000000,12545.000000,12506.000000,12494.000000,...,12628.000000,12489.000000,12491.000000,12517.000000,12440.000000,12530.000000,12547.000000,12510.000000,12480.000000,12401.000000
mean,2.488085e+00,2.507221,2.505893,2.520863,2.489419,2.496008,2.516159,2.497037,2.525902,2.494576,...,2.496966,2.504391,2.512766,2.499413,2.516922,2.503284,2.486547,2.506460,2.495052,2.504067
std,1.431048e+00,1.441092,1.448540,1.450967,1.448868,1.442478,1.458579,1.445208,1.435786,1.432842,...,1.441329,1.450181,1.456648,1.448441,1.438237,1.452780,1.451287,1.445066,1.449894,1.459373
min,1.910715e-07,0.000865,0.000003,0.000056,0.000709,0.000142,0.000172,0.000496,0.000172,0.000002,...,0.000018,0.000127,0.000195,0.000233,0.000073,0.000540,0.000352,0.000625,0.000055,0.000170
25%,1.273875e+00,1.266502,1.236694,1.260030,1.229542,1.233626,1.251759,1.252920,1.298015,1.242821,...,1.239183,1.243464,1.229200,1.232609,1.270294,1.224551,1.214859,1.241506,1.232536,1.235081
50%,2.474292e+00,2.486029,2.501443,2.525176,2.483807,2.498472,2.518660,2.489611,2.534020,2.488015,...,2.498895,2.515233,2.526120,2.492286,2.525108,2.506436,2.479317,2.495833,2.499120,2.499090
75%,3.729182e+00,3.745544,3.772298,3.790788,3.743121,3.744259,3.793889,3.744895,3.769517,3.730720,...,3.738834,3.763128,3.801797,3.758312,3.761003,3.779269,3.753224,3.772277,3.753152,3.797835
max,4.999861e+00,4.999757,4.999873,4.999891,4.999961,4.999339,4.999875,4.999557,4.999828,4.999001,...,4.999544,4.999211,4.998968,4.999930,4.999931,4.999950,4.999496,4.998991,4.999768,4.998911

# 4. PandasのデータとNumpyのデータの相互変換

In [24]:
# Pandasの表をNumpyの配列に変える
data = np.array(df)
data

array([['ID1', nan, nan, ..., 1.259221302423431, 0.7732870517547132,
        1.0287363490062829],
       ['ID2', 'C', 'Z', ..., 0.2210971394155301, 0.976043833946374,
        2.9835332667906647],
       ['ID3', 'A', 'A', ..., nan, 2.4348970290644747, 4.520744788336513],
       ...,
       ['ID14998', 'A', 'C', ..., 4.859076275035232, 4.93298949898281,
        0.3916589553081202],
       ['ID14999', nan, nan, ..., 1.3145171071184372, 2.407776775332024,
        2.731232887542422],
       ['ID15000', 'A', 'B', ..., 3.9455075723675535, 0.9572876312888434,
        nan]], dtype=object)

In [25]:
# データのタイプの確認
type(data)

numpy.ndarray

In [27]:
# 表の1行目の項目名(key)の取得
keys = df.columns
keys

Index(['ID', 'factor1', 'factor2', 'factor3', 'factor4', 'factor5', 'factor6',
       'factor7', 'factor8', 'factor9',
       ...
       'factor141', 'factor142', 'factor143', 'factor144', 'factor145',
       'factor146', 'factor147', 'factor148', 'factor149', 'factor150'],
      dtype='object', length=151)

In [28]:
# 表の項目名も含めてNumpyの配列をPandasの表に変換する
df = pd.DataFrame(data, columns = keys)
df

,ID,factor1,factor2,factor3,factor4,factor5,factor6,factor7,factor8,factor9,...,factor141,factor142,factor143,factor144,factor145,factor146,factor147,factor148,factor149,factor150
0,ID1,NaN,NaN,A,NaN,NaN,1.241863,B,NaN,0.984801,...,1.369706,3.965898,C,3.511195,A,NaN,4.951736,1.259221,0.773287,1.028736
1,ID2,C,Z,Z,0.283582,A,0.24388,Z,A,2.599852,...,3.351286,1.501172,Z,1.029643,A,4.022659,1.036468,0.221097,0.976044,2.983533
2,ID3,A,A,C,3.17593,C,4.365006,A,C,1.650896,...,3.17593,4.225075,C,1.944667,Z,0.651723,4.186858,NaN,2.434897,4.520745
3,ID4,A,Z,A,1.566577,A,2.983811,C,Z,NaN,...,4.724513,2.689592,B,1.428877,C,1.2863,NaN,4.652309,1.428877,3.36287
4,ID5,C,Z,NaN,0.464134,Z,2.191147,NaN,B,4.382401,...,3.137875,4.642228,NaN,4.684253,Z,0.708323,0.808047,0.581696,4.782386,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,ID14996,B,Z,NaN,2.197228,NaN,4.384694,C,A,NaN,...,2.588611,2.877683,B,4.781191,NaN,0.224341,0.143134,2.340001,0.224341,4.952754
14996,ID14997,A,C,A,4.077054,Z,0.44539,C,NaN,2.824001,...,0.779132,0.49173,NaN,NaN,Z,2.614576,2.299104,2.843733,4.20113,0.097627
14997,ID14998,A,C,Z,1.407224,B,2.360011,B,A,2.511333,...,2.044176,2.511333,Z,3.706377,B,NaN,1.562139,4.859076,4.932989,0.391659
14998,ID14999,NaN,NaN,Z,NaN,A,4.059424,NaN,NaN,2.878456,...,NaN,4.732487,B,NaN,B,4.666555,2.699051,1.314517,2.407777,2.731233
14999,ID15000,A,B,A,4.072493,A,4.335164,C,C,3.738258,...,2.143087,4.569763,B,1.045792,B,NaN,4.319808,3.945508,0.957288,NaN